name: MacOS Packaged.

on:
  push:
    branches: [ "614" ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/mac_packaged.yml'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'Telegram/build/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/Resources/winrc/**'
      - 'Telegram/SourceFiles/platform/win/**'
      - 'Telegram/SourceFiles/platform/linux/**'
      - 'Telegram/configure.bat'
  pull_request:
    branches: [ "614" ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/mac_packaged.yml'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'Telegram/build/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/Resources/winrc/**'
      - 'Telegram/SourceFiles/platform/win/**'
      - 'Telegram/SourceFiles/platform/linux/**'
      - 'Telegram/configure.bat'
  workflow_dispatch:

jobs:
  macos:
    name: MacOS
    runs-on: macos-latest   # как у них (ARM раннер)
    timeout-minutes: 240

    env:
      GIT: "https://github.com"
      CMAKE_PREFIX_PATH: "/opt/homebrew/opt/ffmpeg@6:/opt/homebrew/opt/openal-soft"
      UPLOAD_ARTIFACT: "true"
      ONLY_CACHE: "false"
      MANUAL_CACHING: "1"
      AUTO_CACHING: "1"

    steps:
      - name: Get repository name.
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Clone.
        uses: actions/checkout@v5
        with:
          submodules: recursive
          path: ${{ env.REPO_NAME }}

      - name: First set up.
        run: |
          brew update
          brew upgrade || true
          brew install ada-url autoconf automake boost cmake ffmpeg@6 jpeg-xl libavif libheif libtool openal-soft openh264 openssl opus ninja pkg-config python qt yasm xz
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

          xcodebuild -version > CACHE_KEY.txt
          brew list --versions >> CACHE_KEY.txt
          echo $MANUAL_CACHING >> CACHE_KEY.txt
          echo "$GITHUB_WORKSPACE" >> CACHE_KEY.txt
          if [ "$AUTO_CACHING" = "1" ]; then
            thisFile=$REPO_NAME/.github/workflows/mac_packaged.yml
            echo `md5 -q $thisFile` >> CACHE_KEY.txt
          fi
          echo "CACHE_KEY=`md5 -q CACHE_KEY.txt`" >> $GITHUB_ENV

          echo "MACOSX_DEPLOYMENT_TARGET=$(grep 'set(QT_SUPPORTED_MIN_MACOS_VERSION' /opt/homebrew/Cellar/qt/*/lib/cmake/Qt6/Qt6ConfigExtras.cmake | sed -E 's/^.*\"(.*)\".*$/\1/')" >> $GITHUB_ENV
          echo "LibrariesPath=`pwd`" >> $GITHUB_ENV

          curl -o tg_owt-version.json https://api.github.com/repos/desktop-app/tg_owt/git/refs/heads/master

      # --- ДОБАВЛЕНО: вырубаем системный Abseil, чтобы не перебивал вендорный ---
      - name: Safety – remove Homebrew Abseil
        run: |
          brew unlink abseil || brew remove -f abseil || true
          unset CPLUS_INCLUDE_PATH
          unset CPATH

      - name: RNNoise.
        run: |
          cd $LibrariesPath
          git clone --depth=1 https://gitlab.xiph.org/xiph/rnnoise.git
          cd rnnoise
          ./autogen.sh
          ./configure --disable-examples --disable-doc
          make -j$(sysctl -n hw.logicalcpu)
          sudo make install

      - name: WebRTC cache.
        id: cache-webrtc
        uses: actions/cache@v4
        with:
          path: ${{ env.LibrariesPath }}/tg_owt
          key: ${{ runner.OS }}-webrtc-${{ env.CACHE_KEY }}-${{ hashFiles('**/tg_owt-version.json') }}

      # --- МИНИ-ПАТЧ tg_owt, чтобы ObjC++ брал vendor Abseil первым ---
      - name: WebRTC.
        if: steps.cache-webrtc.outputs.cache-hit != 'true'
        run: |
          set -e
          cd $LibrariesPath
          git clone --depth=1 --recursive --shallow-submodules $GIT/desktop-app/tg_owt.git
          cd tg_owt

          VENDOR_ABSL="$PWD/src/third_party/abseil-cpp"
          # 1) Закрепляем приоритет vendor Abseil для ObjC++-библиотеки (где падает RTCVideo*VP8.mm)
          OBJC_CM="$PWD/src/sdk/objc/CMakeLists.txt"
          if ! grep -q "target_include_directories(libsdkmacos" "$OBJC_CM" 2>/dev/null; then
            cat >> "$OBJC_CM" <<EOF

          # Inject vendor Abseil first for ObjC++
          if (TARGET libsdkmacos)
            target_include_directories(libsdkmacos PRIVATE "${VENDOR_ABSL}")
          endif()
          EOF
          fi
          # 2) И глобально ставим vendor Abseil раньше системных для C/C++
          ROOT_CM="$PWD/CMakeLists.txt"
          if ! grep -q "include_directories(BEFORE" "$ROOT_CM"; then
            echo "include_directories(BEFORE \"${VENDOR_ABSL}\")" >> "$ROOT_CM"
          fi

          cmake -Bbuild -GNinja . \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_NO_SYSTEM_FROM_IMPORTED=ON \
            -DCMAKE_INCLUDE_DIRECTORIES_BEFORE=ON \
            -DCMAKE_C_FLAGS_DEBUG="" \
            -DCMAKE_CXX_FLAGS_DEBUG=""

          # sanity: убедимся, что ObjC++ команды реально видят abseil-cpp
          grep -E '"file":.*RTCVideo(Encoder|Decoder)VP8\.mm' -n build/compile_commands.json -A1 | head -n 10 || true
          grep -E '"command".*RTCVideo(Encoder|Decoder)VP8\.mm' build/compile_commands.json | head -n 1 | sed 's/ -/ \n-/g' | grep -q "abseil-cpp" || (echo "vendor Abseil not in OBJCXX compile command"; exit 1)

          cmake --build build --parallel

      - name: TDE2E cache.
        id: cache-tde2e
        uses: actions/cache@v4
        with:
          path: ${{ env.LibrariesPath }}/tde2e
          key: ${{ runner.OS }}-tde2e-${{ env.CACHE_KEY }}

      - name: TDE2E.
        if: steps.cache-tde2e.outputs.cache-hit != 'true'
        run: |
          cd $LibrariesPath
          git init tde2e
          cd tde2e
          git remote add origin $GIT/tdlib/td.git
          git fetch --depth=1 origin 51743dfd01dff6179e2d8f7095729caa4e2222e9
          git reset --hard FETCH_HEAD

          cmake -Bbuild -GNinja . \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_INSTALL_PREFIX=$PWD/build/prefix \
            -DCMAKE_C_FLAGS_DEBUG="" \
            -DCMAKE_CXX_FLAGS_DEBUG="" \
            -DTD_E2E_ONLY=ON
          cmake --build build --parallel
          cmake --install build

      - name: Telegram Desktop build.
        if: env.ONLY_CACHE == 'false'
        env:
          tg_owt_DIR: ${{ env.LibrariesPath }}/tg_owt/build
          tde2e_DIR: ${{ env.LibrariesPath }}/tde2e/build/prefix
        run: |
          cd $REPO_NAME

          DEFINE=""
          if [ -n "${{ matrix.defines }}" ]; then
            DEFINE="-D ${{ matrix.defines }}=ON"
            echo Define from matrix: $DEFINE
            echo "ARTIFACT_NAME=Telegram_${{ matrix.defines }}" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=Telegram" >> $GITHUB_ENV
          fi

          cmake -Bbuild -GNinja . \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_FLAGS_DEBUG="" \
            -DCMAKE_CXX_FLAGS_DEBUG="" \
            -DTDESKTOP_API_TEST=ON \
            $DEFINE

          cmake --build build --parallel

          cd build
          macdeployqt Telegram.app
          codesign --remove-signature Telegram.app

          mkdir dmgsrc
          mv Telegram.app dmgsrc
          hdiutil create -volname Telegram -srcfolder dmgsrc -ov -format UDZO Telegram.dmg

      - name: Move artifact.
        if: env.UPLOAD_ARTIFACT == 'true'
        run: |
          cd $REPO_NAME/build
          mkdir artifact
          mv Telegram.dmg artifact/

      - uses: actions/upload-artifact@v4
        if: env.UPLOAD_ARTIFACT == 'true'
        name: Upload artifact.
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.REPO_NAME }}/build/artifact/
